################################################################################
#
#   Autore          :   Filippo Fresilli & Allan Nava
#   Modificato      :   Filippo Fresilli & Allan Nava
#   Data            :   01/06/2020
#   Aggiornamento   :   05/06/2020
#
#
#################################################################################
#
name: mlcoin_app
description: ml coin flutter app
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
#
environment:
  sdk: ">=2.7.0 <3.0.0"
#
dependencies:
  flutter:
    sdk: flutter
  #
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.4.0
  dio: ^3.0.9
  shared_preferences: ^0.5.6+3
  cached_network_image: ^2.0.0
  body_parser: ^1.1.1
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  tflite: ^1.0.6
  camera: ^0.5.8+2
  flutter_svg:
  #tflite: ^1.0.6
  #video_player: ^0.10.0
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.4.0+9
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2
  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.14.0+5
  #firebase_admob: ^0.9.3+2
  #
  #
#
dev_dependencies:
  flutter_test:
    sdk: flutter
#
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - i18n/en.json
    - i18n/fr.json
    - i18n/it.json
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#
